// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using gym_prog.Data.Data;

#nullable disable

namespace gym_prog.Data.Migrations
{
    [DbContext(typeof(GymContext))]
    [Migration("20250409141235_MoreSeedData")]
    partial class MoreSeedData
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "8.0.14")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("gym_prog.Data.Entities.Exercise", b =>
                {
                    b.Property<string>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("nvarchar(450)")
                        .HasDefaultValueSql("NEWID()");

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("Reps")
                        .HasColumnType("int");

                    b.Property<int>("Sets")
                        .HasColumnType("int");

                    b.Property<int>("Weight")
                        .HasColumnType("int");

                    b.Property<string>("WorkoutId")
                        .HasColumnType("nvarchar(450)");

                    b.HasKey("Id");

                    b.HasIndex("WorkoutId");

                    b.ToTable("Exercises");

                    b.HasData(
                        new
                        {
                            Id = "squat-m1-w1",
                            Description = "Compound exercise targeting quads, hamstrings, and glutes",
                            Name = "Squats",
                            Reps = 8,
                            Sets = 3,
                            Weight = 40,
                            WorkoutId = "workout-m1-w1"
                        },
                        new
                        {
                            Id = "squat-m1-w3",
                            Description = "Compound exercise targeting quads, hamstrings, and glutes",
                            Name = "Squats",
                            Reps = 10,
                            Sets = 3,
                            Weight = 40,
                            WorkoutId = "workout-m1-w3"
                        },
                        new
                        {
                            Id = "squat-m1-w4",
                            Description = "Compound exercise targeting quads, hamstrings, and glutes",
                            Name = "Squats",
                            Reps = 12,
                            Sets = 3,
                            Weight = 40,
                            WorkoutId = "workout-m1-w4"
                        },
                        new
                        {
                            Id = "squat-m1-w6",
                            Description = "Compound exercise targeting quads, hamstrings, and glutes",
                            Name = "Squats",
                            Reps = 8,
                            Sets = 4,
                            Weight = 45,
                            WorkoutId = "workout-m1-w6"
                        },
                        new
                        {
                            Id = "squat-m2-w1",
                            Description = "Compound exercise targeting quads, hamstrings, and glutes",
                            Name = "Squats",
                            Reps = 10,
                            Sets = 4,
                            Weight = 45,
                            WorkoutId = "workout-m2-w1"
                        },
                        new
                        {
                            Id = "squat-m2-w3",
                            Description = "Compound exercise targeting quads, hamstrings, and glutes",
                            Name = "Squats",
                            Reps = 12,
                            Sets = 4,
                            Weight = 45,
                            WorkoutId = "workout-m2-w3"
                        },
                        new
                        {
                            Id = "squat-m2-w4",
                            Description = "Compound exercise targeting quads, hamstrings, and glutes",
                            Name = "Squats",
                            Reps = 8,
                            Sets = 4,
                            Weight = 50,
                            WorkoutId = "workout-m2-w4"
                        },
                        new
                        {
                            Id = "squat-m2-w6",
                            Description = "Compound exercise targeting quads, hamstrings, and glutes",
                            Name = "Squats",
                            Reps = 10,
                            Sets = 4,
                            Weight = 50,
                            WorkoutId = "workout-m2-w6"
                        },
                        new
                        {
                            Id = "squat-m3-w1",
                            Description = "Compound exercise targeting quads, hamstrings, and glutes",
                            Name = "Squats",
                            Reps = 12,
                            Sets = 4,
                            Weight = 50,
                            WorkoutId = "workout-m3-w1"
                        },
                        new
                        {
                            Id = "squat-m3-w3",
                            Description = "Compound exercise targeting quads, hamstrings, and glutes",
                            Name = "Squats",
                            Reps = 10,
                            Sets = 4,
                            Weight = 55,
                            WorkoutId = "workout-m3-w3"
                        },
                        new
                        {
                            Id = "squat-m3-w4",
                            Description = "Compound exercise targeting quads, hamstrings, and glutes",
                            Name = "Squats",
                            Reps = 12,
                            Sets = 4,
                            Weight = 55,
                            WorkoutId = "workout-m3-w4"
                        },
                        new
                        {
                            Id = "squat-m3-w6",
                            Description = "Compound exercise targeting quads, hamstrings, and glutes",
                            Name = "Squats",
                            Reps = 12,
                            Sets = 4,
                            Weight = 60,
                            WorkoutId = "workout-m3-w6"
                        },
                        new
                        {
                            Id = "1e2f3a4b-5c6d-7e8f-9a0b-1c2d3e4f5a6b",
                            Description = "Compound exercise targeting quads, hamstrings, and glutes",
                            Name = "Squats",
                            Reps = 12,
                            Sets = 4,
                            Weight = 60,
                            WorkoutId = "1a2b3c4d-5e6f-7a8b-9c0d-1e2f3a4b5c6d"
                        },
                        new
                        {
                            Id = "bench-m1-w1",
                            Description = "Compound exercise for chest, shoulders, and triceps",
                            Name = "Bench Press",
                            Reps = 8,
                            Sets = 3,
                            Weight = 30,
                            WorkoutId = "workout-m1-w1"
                        },
                        new
                        {
                            Id = "bench-m1-w2",
                            Description = "Compound exercise for chest, shoulders, and triceps",
                            Name = "Bench Press",
                            Reps = 10,
                            Sets = 3,
                            Weight = 30,
                            WorkoutId = "workout-m1-w2"
                        },
                        new
                        {
                            Id = "bench-m1-w4",
                            Description = "Compound exercise for chest, shoulders, and triceps",
                            Name = "Bench Press",
                            Reps = 12,
                            Sets = 3,
                            Weight = 30,
                            WorkoutId = "workout-m1-w4"
                        },
                        new
                        {
                            Id = "bench-m1-w5",
                            Description = "Compound exercise for chest, shoulders, and triceps",
                            Name = "Bench Press",
                            Reps = 8,
                            Sets = 3,
                            Weight = 35,
                            WorkoutId = "workout-m1-w5"
                        },
                        new
                        {
                            Id = "bench-m2-w1",
                            Description = "Compound exercise for chest, shoulders, and triceps",
                            Name = "Bench Press",
                            Reps = 10,
                            Sets = 3,
                            Weight = 35,
                            WorkoutId = "workout-m2-w1"
                        },
                        new
                        {
                            Id = "bench-m2-w2",
                            Description = "Compound exercise for chest, shoulders, and triceps",
                            Name = "Bench Press",
                            Reps = 12,
                            Sets = 3,
                            Weight = 35,
                            WorkoutId = "workout-m2-w2"
                        },
                        new
                        {
                            Id = "bench-m2-w4",
                            Description = "Compound exercise for chest, shoulders, and triceps",
                            Name = "Bench Press",
                            Reps = 8,
                            Sets = 3,
                            Weight = 40,
                            WorkoutId = "workout-m2-w4"
                        },
                        new
                        {
                            Id = "bench-m2-w5",
                            Description = "Compound exercise for chest, shoulders, and triceps",
                            Name = "Bench Press",
                            Reps = 10,
                            Sets = 3,
                            Weight = 40,
                            WorkoutId = "workout-m2-w5"
                        },
                        new
                        {
                            Id = "bench-m3-w1",
                            Description = "Compound exercise for chest, shoulders, and triceps",
                            Name = "Bench Press",
                            Reps = 12,
                            Sets = 3,
                            Weight = 40,
                            WorkoutId = "workout-m3-w1"
                        },
                        new
                        {
                            Id = "bench-m3-w2",
                            Description = "Compound exercise for chest, shoulders, and triceps",
                            Name = "Bench Press",
                            Reps = 8,
                            Sets = 3,
                            Weight = 45,
                            WorkoutId = "workout-m3-w2"
                        },
                        new
                        {
                            Id = "bench-m3-w4",
                            Description = "Compound exercise for chest, shoulders, and triceps",
                            Name = "Bench Press",
                            Reps = 10,
                            Sets = 3,
                            Weight = 45,
                            WorkoutId = "workout-m3-w4"
                        },
                        new
                        {
                            Id = "bench-m3-w5",
                            Description = "Compound exercise for chest, shoulders, and triceps",
                            Name = "Bench Press",
                            Reps = 10,
                            Sets = 3,
                            Weight = 50,
                            WorkoutId = "workout-m3-w5"
                        },
                        new
                        {
                            Id = "2f3a4b5c-6d7e-8f9a-0b1c-2d3e4f5a6b7c",
                            Description = "Compound exercise for chest, shoulders, and triceps",
                            Name = "Bench Press",
                            Reps = 10,
                            Sets = 3,
                            Weight = 50,
                            WorkoutId = "1a2b3c4d-5e6f-7a8b-9c0d-1e2f3a4b5c6d"
                        },
                        new
                        {
                            Id = "deadlift-m1-w1",
                            Description = "Full body compound exercise emphasizing posterior chain",
                            Name = "Deadlifts",
                            Reps = 6,
                            Sets = 3,
                            Weight = 50,
                            WorkoutId = "workout-m1-w1"
                        },
                        new
                        {
                            Id = "deadlift-m1-w3",
                            Description = "Full body compound exercise emphasizing posterior chain",
                            Name = "Deadlifts",
                            Reps = 8,
                            Sets = 3,
                            Weight = 50,
                            WorkoutId = "workout-m1-w3"
                        },
                        new
                        {
                            Id = "deadlift-m1-w4",
                            Description = "Full body compound exercise emphasizing posterior chain",
                            Name = "Deadlifts",
                            Reps = 6,
                            Sets = 4,
                            Weight = 55,
                            WorkoutId = "workout-m1-w4"
                        },
                        new
                        {
                            Id = "deadlift-m1-w6",
                            Description = "Full body compound exercise emphasizing posterior chain",
                            Name = "Deadlifts",
                            Reps = 8,
                            Sets = 4,
                            Weight = 55,
                            WorkoutId = "workout-m1-w6"
                        },
                        new
                        {
                            Id = "deadlift-m2-w1",
                            Description = "Full body compound exercise emphasizing posterior chain",
                            Name = "Deadlifts",
                            Reps = 6,
                            Sets = 4,
                            Weight = 60,
                            WorkoutId = "workout-m2-w1"
                        },
                        new
                        {
                            Id = "deadlift-m2-w3",
                            Description = "Full body compound exercise emphasizing posterior chain",
                            Name = "Deadlifts",
                            Reps = 8,
                            Sets = 4,
                            Weight = 60,
                            WorkoutId = "workout-m2-w3"
                        },
                        new
                        {
                            Id = "deadlift-m2-w4",
                            Description = "Full body compound exercise emphasizing posterior chain",
                            Name = "Deadlifts",
                            Reps = 6,
                            Sets = 4,
                            Weight = 70,
                            WorkoutId = "workout-m2-w4"
                        },
                        new
                        {
                            Id = "deadlift-m2-w6",
                            Description = "Full body compound exercise emphasizing posterior chain",
                            Name = "Deadlifts",
                            Reps = 8,
                            Sets = 4,
                            Weight = 70,
                            WorkoutId = "workout-m2-w6"
                        },
                        new
                        {
                            Id = "deadlift-m3-w1",
                            Description = "Full body compound exercise emphasizing posterior chain",
                            Name = "Deadlifts",
                            Reps = 6,
                            Sets = 4,
                            Weight = 75,
                            WorkoutId = "workout-m3-w1"
                        },
                        new
                        {
                            Id = "deadlift-m3-w3",
                            Description = "Full body compound exercise emphasizing posterior chain",
                            Name = "Deadlifts",
                            Reps = 8,
                            Sets = 4,
                            Weight = 75,
                            WorkoutId = "workout-m3-w3"
                        },
                        new
                        {
                            Id = "deadlift-m3-w4",
                            Description = "Full body compound exercise emphasizing posterior chain",
                            Name = "Deadlifts",
                            Reps = 6,
                            Sets = 4,
                            Weight = 80,
                            WorkoutId = "workout-m3-w4"
                        },
                        new
                        {
                            Id = "deadlift-m3-w6",
                            Description = "Full body compound exercise emphasizing posterior chain",
                            Name = "Deadlifts",
                            Reps = 8,
                            Sets = 4,
                            Weight = 80,
                            WorkoutId = "workout-m3-w6"
                        },
                        new
                        {
                            Id = "3a4b5c6d-7e8f-9a0b-1c2d-3e4f5a6b7c8d",
                            Description = "Full body compound exercise emphasizing posterior chain",
                            Name = "Deadlifts",
                            Reps = 8,
                            Sets = 4,
                            Weight = 80,
                            WorkoutId = "1a2b3c4d-5e6f-7a8b-9c0d-1e2f3a4b5c6d"
                        },
                        new
                        {
                            Id = "pullup-m1-w1",
                            Description = "Bodyweight exercise targeting back and biceps",
                            Name = "Pull-ups",
                            Reps = 5,
                            Sets = 2,
                            Weight = 0,
                            WorkoutId = "workout-m1-w1"
                        },
                        new
                        {
                            Id = "pullup-m1-w2",
                            Description = "Bodyweight exercise targeting back and biceps",
                            Name = "Pull-ups",
                            Reps = 6,
                            Sets = 2,
                            Weight = 0,
                            WorkoutId = "workout-m1-w2"
                        },
                        new
                        {
                            Id = "pullup-m1-w4",
                            Description = "Bodyweight exercise targeting back and biceps",
                            Name = "Pull-ups",
                            Reps = 5,
                            Sets = 3,
                            Weight = 0,
                            WorkoutId = "workout-m1-w4"
                        },
                        new
                        {
                            Id = "pullup-m1-w5",
                            Description = "Bodyweight exercise targeting back and biceps",
                            Name = "Pull-ups",
                            Reps = 6,
                            Sets = 3,
                            Weight = 0,
                            WorkoutId = "workout-m1-w5"
                        },
                        new
                        {
                            Id = "pullup-m2-w1",
                            Description = "Bodyweight exercise targeting back and biceps",
                            Name = "Pull-ups",
                            Reps = 6,
                            Sets = 3,
                            Weight = 0,
                            WorkoutId = "workout-m2-w1"
                        },
                        new
                        {
                            Id = "pullup-m2-w2",
                            Description = "Bodyweight exercise targeting back and biceps",
                            Name = "Pull-ups",
                            Reps = 7,
                            Sets = 3,
                            Weight = 0,
                            WorkoutId = "workout-m2-w2"
                        },
                        new
                        {
                            Id = "pullup-m2-w4",
                            Description = "Bodyweight exercise targeting back and biceps",
                            Name = "Pull-ups",
                            Reps = 7,
                            Sets = 3,
                            Weight = 0,
                            WorkoutId = "workout-m2-w4"
                        },
                        new
                        {
                            Id = "pullup-m2-w5",
                            Description = "Bodyweight exercise targeting back and biceps",
                            Name = "Pull-ups",
                            Reps = 8,
                            Sets = 3,
                            Weight = 0,
                            WorkoutId = "workout-m2-w5"
                        },
                        new
                        {
                            Id = "pullup-m3-w1",
                            Description = "Bodyweight exercise targeting back and biceps",
                            Name = "Pull-ups",
                            Reps = 8,
                            Sets = 3,
                            Weight = 0,
                            WorkoutId = "workout-m3-w1"
                        },
                        new
                        {
                            Id = "pullup-m3-w2",
                            Description = "Bodyweight exercise targeting back and biceps",
                            Name = "Pull-ups",
                            Reps = 8,
                            Sets = 3,
                            Weight = 0,
                            WorkoutId = "workout-m3-w2"
                        },
                        new
                        {
                            Id = "pullup-m3-w4",
                            Description = "Bodyweight exercise targeting back and biceps",
                            Name = "Pull-ups",
                            Reps = 8,
                            Sets = 3,
                            Weight = 0,
                            WorkoutId = "workout-m3-w4"
                        },
                        new
                        {
                            Id = "pullup-m3-w5",
                            Description = "Bodyweight exercise targeting back and biceps",
                            Name = "Pull-ups",
                            Reps = 8,
                            Sets = 3,
                            Weight = 0,
                            WorkoutId = "workout-m3-w5"
                        },
                        new
                        {
                            Id = "4b5c6d7e-8f9a-0b1c-2d3e-4f5a6b7c8d9e",
                            Description = "Bodyweight exercise targeting back and biceps",
                            Name = "Pull-ups",
                            Reps = 8,
                            Sets = 3,
                            Weight = 0,
                            WorkoutId = "2b3c4d5e-6f7a-8b9c-0d1e-2f3a4b5c6d7e"
                        },
                        new
                        {
                            Id = "shoulder-m1-w1",
                            Description = "Overhead press targeting deltoids and triceps",
                            Name = "Shoulder Press",
                            Reps = 8,
                            Sets = 3,
                            Weight = 20,
                            WorkoutId = "workout-m1-w1"
                        },
                        new
                        {
                            Id = "shoulder-m1-w2",
                            Description = "Overhead press targeting deltoids and triceps",
                            Name = "Shoulder Press",
                            Reps = 10,
                            Sets = 3,
                            Weight = 20,
                            WorkoutId = "workout-m1-w2"
                        },
                        new
                        {
                            Id = "shoulder-m1-w4",
                            Description = "Overhead press targeting deltoids and triceps",
                            Name = "Shoulder Press",
                            Reps = 12,
                            Sets = 3,
                            Weight = 20,
                            WorkoutId = "workout-m1-w4"
                        },
                        new
                        {
                            Id = "shoulder-m1-w5",
                            Description = "Overhead press targeting deltoids and triceps",
                            Name = "Shoulder Press",
                            Reps = 8,
                            Sets = 3,
                            Weight = 25,
                            WorkoutId = "workout-m1-w5"
                        },
                        new
                        {
                            Id = "shoulder-m2-w1",
                            Description = "Overhead press targeting deltoids and triceps",
                            Name = "Shoulder Press",
                            Reps = 10,
                            Sets = 3,
                            Weight = 25,
                            WorkoutId = "workout-m2-w1"
                        },
                        new
                        {
                            Id = "shoulder-m2-w2",
                            Description = "Overhead press targeting deltoids and triceps",
                            Name = "Shoulder Press",
                            Reps = 12,
                            Sets = 3,
                            Weight = 25,
                            WorkoutId = "workout-m2-w2"
                        },
                        new
                        {
                            Id = "shoulder-m2-w4",
                            Description = "Overhead press targeting deltoids and triceps",
                            Name = "Shoulder Press",
                            Reps = 8,
                            Sets = 3,
                            Weight = 30,
                            WorkoutId = "workout-m2-w4"
                        },
                        new
                        {
                            Id = "shoulder-m2-w5",
                            Description = "Overhead press targeting deltoids and triceps",
                            Name = "Shoulder Press",
                            Reps = 10,
                            Sets = 3,
                            Weight = 30,
                            WorkoutId = "workout-m2-w5"
                        },
                        new
                        {
                            Id = "shoulder-m3-w1",
                            Description = "Overhead press targeting deltoids and triceps",
                            Name = "Shoulder Press",
                            Reps = 12,
                            Sets = 3,
                            Weight = 30,
                            WorkoutId = "workout-m3-w1"
                        },
                        new
                        {
                            Id = "shoulder-m3-w2",
                            Description = "Overhead press targeting deltoids and triceps",
                            Name = "Shoulder Press",
                            Reps = 10,
                            Sets = 3,
                            Weight = 35,
                            WorkoutId = "workout-m3-w2"
                        },
                        new
                        {
                            Id = "shoulder-m3-w4",
                            Description = "Overhead press targeting deltoids and triceps",
                            Name = "Shoulder Press",
                            Reps = 12,
                            Sets = 3,
                            Weight = 35,
                            WorkoutId = "workout-m3-w4"
                        },
                        new
                        {
                            Id = "shoulder-m3-w5",
                            Description = "Overhead press targeting deltoids and triceps",
                            Name = "Shoulder Press",
                            Reps = 12,
                            Sets = 3,
                            Weight = 40,
                            WorkoutId = "workout-m3-w5"
                        },
                        new
                        {
                            Id = "5c6d7e8f-9a0b-1c2d-3e4f-5a6b7c8d9e0f",
                            Description = "Overhead press targeting deltoids and triceps",
                            Name = "Shoulder Press",
                            Reps = 12,
                            Sets = 3,
                            Weight = 40,
                            WorkoutId = "2b3c4d5e-6f7a-8b9c-0d1e-2f3a4b5c6d7e"
                        },
                        new
                        {
                            Id = "bicep-m1-w1",
                            Description = "Isolation exercise for biceps",
                            Name = "Bicep Curls",
                            Reps = 10,
                            Sets = 3,
                            Weight = 8,
                            WorkoutId = "workout-m1-w1"
                        },
                        new
                        {
                            Id = "bicep-m1-w2",
                            Description = "Isolation exercise for biceps",
                            Name = "Bicep Curls",
                            Reps = 12,
                            Sets = 3,
                            Weight = 8,
                            WorkoutId = "workout-m1-w2"
                        },
                        new
                        {
                            Id = "bicep-m1-w4",
                            Description = "Isolation exercise for biceps",
                            Name = "Bicep Curls",
                            Reps = 15,
                            Sets = 3,
                            Weight = 8,
                            WorkoutId = "workout-m1-w4"
                        },
                        new
                        {
                            Id = "bicep-m1-w5",
                            Description = "Isolation exercise for biceps",
                            Name = "Bicep Curls",
                            Reps = 10,
                            Sets = 3,
                            Weight = 10,
                            WorkoutId = "workout-m1-w5"
                        },
                        new
                        {
                            Id = "bicep-m2-w1",
                            Description = "Isolation exercise for biceps",
                            Name = "Bicep Curls",
                            Reps = 12,
                            Sets = 3,
                            Weight = 10,
                            WorkoutId = "workout-m2-w1"
                        },
                        new
                        {
                            Id = "bicep-m2-w2",
                            Description = "Isolation exercise for biceps",
                            Name = "Bicep Curls",
                            Reps = 15,
                            Sets = 3,
                            Weight = 10,
                            WorkoutId = "workout-m2-w2"
                        },
                        new
                        {
                            Id = "bicep-m2-w4",
                            Description = "Isolation exercise for biceps",
                            Name = "Bicep Curls",
                            Reps = 12,
                            Sets = 3,
                            Weight = 12,
                            WorkoutId = "workout-m2-w4"
                        },
                        new
                        {
                            Id = "bicep-m2-w5",
                            Description = "Isolation exercise for biceps",
                            Name = "Bicep Curls",
                            Reps = 15,
                            Sets = 3,
                            Weight = 12,
                            WorkoutId = "workout-m2-w5"
                        },
                        new
                        {
                            Id = "bicep-m3-w1",
                            Description = "Isolation exercise for biceps",
                            Name = "Bicep Curls",
                            Reps = 12,
                            Sets = 3,
                            Weight = 14,
                            WorkoutId = "workout-m3-w1"
                        },
                        new
                        {
                            Id = "bicep-m3-w2",
                            Description = "Isolation exercise for biceps",
                            Name = "Bicep Curls",
                            Reps = 15,
                            Sets = 3,
                            Weight = 14,
                            WorkoutId = "workout-m3-w2"
                        },
                        new
                        {
                            Id = "bicep-m3-w4",
                            Description = "Isolation exercise for biceps",
                            Name = "Bicep Curls",
                            Reps = 12,
                            Sets = 3,
                            Weight = 15,
                            WorkoutId = "workout-m3-w4"
                        },
                        new
                        {
                            Id = "bicep-m3-w5",
                            Description = "Isolation exercise for biceps",
                            Name = "Bicep Curls",
                            Reps = 15,
                            Sets = 3,
                            Weight = 15,
                            WorkoutId = "workout-m3-w5"
                        },
                        new
                        {
                            Id = "6d7e8f9a-0b1c-2d3e-4f5a-6b7c8d9e0f1a",
                            Description = "Isolation exercise for biceps",
                            Name = "Bicep Curls",
                            Reps = 15,
                            Sets = 3,
                            Weight = 15,
                            WorkoutId = "2b3c4d5e-6f7a-8b9c-0d1e-2f3a4b5c6d7e"
                        },
                        new
                        {
                            Id = "legpress-m1-w1",
                            Description = "Machine-based compound leg exercise",
                            Name = "Leg Press",
                            Reps = 10,
                            Sets = 3,
                            Weight = 60,
                            WorkoutId = "workout-m1-w1"
                        },
                        new
                        {
                            Id = "legpress-m1-w3",
                            Description = "Machine-based compound leg exercise",
                            Name = "Leg Press",
                            Reps = 12,
                            Sets = 3,
                            Weight = 60,
                            WorkoutId = "workout-m1-w3"
                        },
                        new
                        {
                            Id = "legpress-m1-w4",
                            Description = "Machine-based compound leg exercise",
                            Name = "Leg Press",
                            Reps = 10,
                            Sets = 4,
                            Weight = 70,
                            WorkoutId = "workout-m1-w4"
                        },
                        new
                        {
                            Id = "legpress-m1-w6",
                            Description = "Machine-based compound leg exercise",
                            Name = "Leg Press",
                            Reps = 12,
                            Sets = 4,
                            Weight = 70,
                            WorkoutId = "workout-m1-w6"
                        },
                        new
                        {
                            Id = "legpress-m2-w1",
                            Description = "Machine-based compound leg exercise",
                            Name = "Leg Press",
                            Reps = 10,
                            Sets = 4,
                            Weight = 80,
                            WorkoutId = "workout-m2-w1"
                        },
                        new
                        {
                            Id = "legpress-m2-w3",
                            Description = "Machine-based compound leg exercise",
                            Name = "Leg Press",
                            Reps = 12,
                            Sets = 4,
                            Weight = 80,
                            WorkoutId = "workout-m2-w3"
                        },
                        new
                        {
                            Id = "legpress-m2-w4",
                            Description = "Machine-based compound leg exercise",
                            Name = "Leg Press",
                            Reps = 10,
                            Sets = 4,
                            Weight = 90,
                            WorkoutId = "workout-m2-w4"
                        },
                        new
                        {
                            Id = "legpress-m2-w6",
                            Description = "Machine-based compound leg exercise",
                            Name = "Leg Press",
                            Reps = 12,
                            Sets = 4,
                            Weight = 90,
                            WorkoutId = "workout-m2-w6"
                        },
                        new
                        {
                            Id = "legpress-m3-w1",
                            Description = "Machine-based compound leg exercise",
                            Name = "Leg Press",
                            Reps = 10,
                            Sets = 4,
                            Weight = 100,
                            WorkoutId = "workout-m3-w1"
                        },
                        new
                        {
                            Id = "legpress-m3-w3",
                            Description = "Machine-based compound leg exercise",
                            Name = "Leg Press",
                            Reps = 12,
                            Sets = 4,
                            Weight = 100,
                            WorkoutId = "workout-m3-w3"
                        },
                        new
                        {
                            Id = "legpress-m3-w4",
                            Description = "Machine-based compound leg exercise",
                            Name = "Leg Press",
                            Reps = 10,
                            Sets = 4,
                            Weight = 100,
                            WorkoutId = "workout-m3-w4"
                        },
                        new
                        {
                            Id = "legpress-m3-w6",
                            Description = "Machine-based compound leg exercise",
                            Name = "Leg Press",
                            Reps = 12,
                            Sets = 4,
                            Weight = 100,
                            WorkoutId = "workout-m3-w6"
                        },
                        new
                        {
                            Id = "7e8f9a0b-1c2d-3e4f-5a6b-7c8d9e0f1a2b",
                            Description = "Machine-based compound leg exercise",
                            Name = "Leg Press",
                            Reps = 12,
                            Sets = 4,
                            Weight = 100,
                            WorkoutId = "3c4d5e6f-7a8b-9c0d-1e2f-3a4b5c6d7e8f"
                        },
                        new
                        {
                            Id = "rdl-m1-w1",
                            Description = "Targets hamstrings and lower back",
                            Name = "Romanian Deadlifts",
                            Reps = 8,
                            Sets = 3,
                            Weight = 40,
                            WorkoutId = "workout-m1-w1"
                        },
                        new
                        {
                            Id = "rdl-m1-w3",
                            Description = "Targets hamstrings and lower back",
                            Name = "Romanian Deadlifts",
                            Reps = 10,
                            Sets = 3,
                            Weight = 40,
                            WorkoutId = "workout-m1-w3"
                        },
                        new
                        {
                            Id = "rdl-m1-w4",
                            Description = "Targets hamstrings and lower back",
                            Name = "Romanian Deadlifts",
                            Reps = 8,
                            Sets = 3,
                            Weight = 45,
                            WorkoutId = "workout-m1-w4"
                        },
                        new
                        {
                            Id = "rdl-m1-w6",
                            Description = "Targets hamstrings and lower back",
                            Name = "Romanian Deadlifts",
                            Reps = 10,
                            Sets = 3,
                            Weight = 45,
                            WorkoutId = "workout-m1-w6"
                        },
                        new
                        {
                            Id = "rdl-m2-w1",
                            Description = "Targets hamstrings and lower back",
                            Name = "Romanian Deadlifts",
                            Reps = 8,
                            Sets = 3,
                            Weight = 50,
                            WorkoutId = "workout-m2-w1"
                        },
                        new
                        {
                            Id = "rdl-m2-w3",
                            Description = "Targets hamstrings and lower back",
                            Name = "Romanian Deadlifts",
                            Reps = 10,
                            Sets = 3,
                            Weight = 50,
                            WorkoutId = "workout-m2-w3"
                        },
                        new
                        {
                            Id = "rdl-m2-w4",
                            Description = "Targets hamstrings and lower back",
                            Name = "Romanian Deadlifts",
                            Reps = 8,
                            Sets = 3,
                            Weight = 60,
                            WorkoutId = "workout-m2-w4"
                        },
                        new
                        {
                            Id = "rdl-m2-w6",
                            Description = "Targets hamstrings and lower back",
                            Name = "Romanian Deadlifts",
                            Reps = 10,
                            Sets = 3,
                            Weight = 60,
                            WorkoutId = "workout-m2-w6"
                        },
                        new
                        {
                            Id = "rdl-m3-w1",
                            Description = "Targets hamstrings and lower back",
                            Name = "Romanian Deadlifts",
                            Reps = 8,
                            Sets = 3,
                            Weight = 65,
                            WorkoutId = "workout-m3-w1"
                        },
                        new
                        {
                            Id = "rdl-m3-w3",
                            Description = "Targets hamstrings and lower back",
                            Name = "Romanian Deadlifts",
                            Reps = 10,
                            Sets = 3,
                            Weight = 65,
                            WorkoutId = "workout-m3-w3"
                        },
                        new
                        {
                            Id = "rdl-m3-w4",
                            Description = "Targets hamstrings and lower back",
                            Name = "Romanian Deadlifts",
                            Reps = 8,
                            Sets = 3,
                            Weight = 70,
                            WorkoutId = "workout-m3-w4"
                        },
                        new
                        {
                            Id = "rdl-m3-w6",
                            Description = "Targets hamstrings and lower back",
                            Name = "Romanian Deadlifts",
                            Reps = 10,
                            Sets = 3,
                            Weight = 70,
                            WorkoutId = "workout-m3-w6"
                        },
                        new
                        {
                            Id = "8f9a0b1c-2d3e-4f5a-6b7c-8d9e0f1a2b3c",
                            Description = "Targets hamstrings and lower back",
                            Name = "Romanian Deadlifts",
                            Reps = 10,
                            Sets = 3,
                            Weight = 70,
                            WorkoutId = "3c4d5e6f-7a8b-9c0d-1e2f-3a4b5c6d7e8f"
                        },
                        new
                        {
                            Id = "calf-m1-w1",
                            Description = "Isolation exercise for calf muscles",
                            Name = "Calf Raises",
                            Reps = 15,
                            Sets = 3,
                            Weight = 10,
                            WorkoutId = "workout-m1-w1"
                        },
                        new
                        {
                            Id = "calf-m1-w3",
                            Description = "Isolation exercise for calf muscles",
                            Name = "Calf Raises",
                            Reps = 18,
                            Sets = 3,
                            Weight = 10,
                            WorkoutId = "workout-m1-w3"
                        },
                        new
                        {
                            Id = "calf-m1-w4",
                            Description = "Isolation exercise for calf muscles",
                            Name = "Calf Raises",
                            Reps = 20,
                            Sets = 3,
                            Weight = 10,
                            WorkoutId = "workout-m1-w4"
                        },
                        new
                        {
                            Id = "calf-m1-w6",
                            Description = "Isolation exercise for calf muscles",
                            Name = "Calf Raises",
                            Reps = 15,
                            Sets = 3,
                            Weight = 15,
                            WorkoutId = "workout-m1-w6"
                        },
                        new
                        {
                            Id = "calf-m2-w1",
                            Description = "Isolation exercise for calf muscles",
                            Name = "Calf Raises",
                            Reps = 18,
                            Sets = 3,
                            Weight = 15,
                            WorkoutId = "workout-m2-w1"
                        },
                        new
                        {
                            Id = "calf-m2-w3",
                            Description = "Isolation exercise for calf muscles",
                            Name = "Calf Raises",
                            Reps = 20,
                            Sets = 3,
                            Weight = 15,
                            WorkoutId = "workout-m2-w3"
                        },
                        new
                        {
                            Id = "calf-m2-w4",
                            Description = "Isolation exercise for calf muscles",
                            Name = "Calf Raises",
                            Reps = 15,
                            Sets = 4,
                            Weight = 20,
                            WorkoutId = "workout-m2-w4"
                        },
                        new
                        {
                            Id = "calf-m2-w6",
                            Description = "Isolation exercise for calf muscles",
                            Name = "Calf Raises",
                            Reps = 18,
                            Sets = 4,
                            Weight = 20,
                            WorkoutId = "workout-m2-w6"
                        },
                        new
                        {
                            Id = "calf-m3-w1",
                            Description = "Isolation exercise for calf muscles",
                            Name = "Calf Raises",
                            Reps = 20,
                            Sets = 4,
                            Weight = 20,
                            WorkoutId = "workout-m3-w1"
                        },
                        new
                        {
                            Id = "calf-m3-w3",
                            Description = "Isolation exercise for calf muscles",
                            Name = "Calf Raises",
                            Reps = 18,
                            Sets = 4,
                            Weight = 25,
                            WorkoutId = "workout-m3-w3"
                        },
                        new
                        {
                            Id = "calf-m3-w4",
                            Description = "Isolation exercise for calf muscles",
                            Name = "Calf Raises",
                            Reps = 20,
                            Sets = 4,
                            Weight = 25,
                            WorkoutId = "workout-m3-w4"
                        },
                        new
                        {
                            Id = "calf-m3-w6",
                            Description = "Isolation exercise for calf muscles",
                            Name = "Calf Raises",
                            Reps = 20,
                            Sets = 4,
                            Weight = 30,
                            WorkoutId = "workout-m3-w6"
                        },
                        new
                        {
                            Id = "9a0b1c2d-3e4f-5a6b-7c8d-9e0f1a2b3c4d",
                            Description = "Isolation exercise for calf muscles",
                            Name = "Calf Raises",
                            Reps = 20,
                            Sets = 4,
                            Weight = 30,
                            WorkoutId = "3c4d5e6f-7a8b-9c0d-1e2f-3a4b5c6d7e8f"
                        });
                });

            modelBuilder.Entity("gym_prog.Data.Entities.Workout", b =>
                {
                    b.Property<string>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("nvarchar(450)")
                        .HasDefaultValueSql("NEWID()");

                    b.Property<DateTime>("Date")
                        .HasColumnType("datetime2");

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.ToTable("Workouts");

                    b.HasData(
                        new
                        {
                            Id = "workout-m1-w1",
                            Date = new DateTime(2025, 1, 15, 17, 12, 35, 246, DateTimeKind.Local).AddTicks(6159),
                            Description = "A comprehensive workout that targets all major muscle groups",
                            Name = "Full Body Workout"
                        },
                        new
                        {
                            Id = "workout-m1-w2",
                            Date = new DateTime(2025, 1, 19, 17, 12, 35, 246, DateTimeKind.Local).AddTicks(6159),
                            Description = "Targets chest, shoulders, back, and arms",
                            Name = "Upper Body Focus"
                        },
                        new
                        {
                            Id = "workout-m1-w3",
                            Date = new DateTime(2025, 1, 22, 17, 12, 35, 246, DateTimeKind.Local).AddTicks(6159),
                            Description = "Focuses on quads, hamstrings, calves, and glutes",
                            Name = "Lower Body Strength"
                        },
                        new
                        {
                            Id = "workout-m1-w4",
                            Date = new DateTime(2025, 1, 29, 17, 12, 35, 246, DateTimeKind.Local).AddTicks(6159),
                            Description = "A comprehensive workout that targets all major muscle groups",
                            Name = "Full Body Workout"
                        },
                        new
                        {
                            Id = "workout-m1-w5",
                            Date = new DateTime(2025, 2, 2, 17, 12, 35, 246, DateTimeKind.Local).AddTicks(6159),
                            Description = "Targets chest, shoulders, back, and arms",
                            Name = "Upper Body Focus"
                        },
                        new
                        {
                            Id = "workout-m1-w6",
                            Date = new DateTime(2025, 2, 5, 17, 12, 35, 246, DateTimeKind.Local).AddTicks(6159),
                            Description = "Focuses on quads, hamstrings, calves, and glutes",
                            Name = "Lower Body Strength"
                        },
                        new
                        {
                            Id = "workout-m2-w1",
                            Date = new DateTime(2025, 2, 12, 17, 12, 35, 246, DateTimeKind.Local).AddTicks(6159),
                            Description = "A comprehensive workout that targets all major muscle groups",
                            Name = "Full Body Workout"
                        },
                        new
                        {
                            Id = "workout-m2-w2",
                            Date = new DateTime(2025, 2, 16, 17, 12, 35, 246, DateTimeKind.Local).AddTicks(6159),
                            Description = "Targets chest, shoulders, back, and arms",
                            Name = "Upper Body Focus"
                        },
                        new
                        {
                            Id = "workout-m2-w3",
                            Date = new DateTime(2025, 2, 19, 17, 12, 35, 246, DateTimeKind.Local).AddTicks(6159),
                            Description = "Focuses on quads, hamstrings, calves, and glutes",
                            Name = "Lower Body Strength"
                        },
                        new
                        {
                            Id = "workout-m2-w4",
                            Date = new DateTime(2025, 2, 26, 17, 12, 35, 246, DateTimeKind.Local).AddTicks(6159),
                            Description = "A comprehensive workout that targets all major muscle groups",
                            Name = "Full Body Workout"
                        },
                        new
                        {
                            Id = "workout-m2-w5",
                            Date = new DateTime(2025, 3, 2, 17, 12, 35, 246, DateTimeKind.Local).AddTicks(6159),
                            Description = "Targets chest, shoulders, back, and arms",
                            Name = "Upper Body Focus"
                        },
                        new
                        {
                            Id = "workout-m2-w6",
                            Date = new DateTime(2025, 3, 5, 17, 12, 35, 246, DateTimeKind.Local).AddTicks(6159),
                            Description = "Focuses on quads, hamstrings, calves, and glutes",
                            Name = "Lower Body Strength"
                        },
                        new
                        {
                            Id = "workout-m3-w1",
                            Date = new DateTime(2025, 3, 12, 17, 12, 35, 246, DateTimeKind.Local).AddTicks(6159),
                            Description = "A comprehensive workout that targets all major muscle groups",
                            Name = "Full Body Workout"
                        },
                        new
                        {
                            Id = "workout-m3-w2",
                            Date = new DateTime(2025, 3, 16, 17, 12, 35, 246, DateTimeKind.Local).AddTicks(6159),
                            Description = "Targets chest, shoulders, back, and arms",
                            Name = "Upper Body Focus"
                        },
                        new
                        {
                            Id = "workout-m3-w3",
                            Date = new DateTime(2025, 3, 19, 17, 12, 35, 246, DateTimeKind.Local).AddTicks(6159),
                            Description = "Focuses on quads, hamstrings, calves, and glutes",
                            Name = "Lower Body Strength"
                        },
                        new
                        {
                            Id = "workout-m3-w4",
                            Date = new DateTime(2025, 3, 26, 17, 12, 35, 246, DateTimeKind.Local).AddTicks(6159),
                            Description = "A comprehensive workout that targets all major muscle groups",
                            Name = "Full Body Workout"
                        },
                        new
                        {
                            Id = "workout-m3-w5",
                            Date = new DateTime(2025, 3, 30, 17, 12, 35, 246, DateTimeKind.Local).AddTicks(6159),
                            Description = "Targets chest, shoulders, back, and arms",
                            Name = "Upper Body Focus"
                        },
                        new
                        {
                            Id = "workout-m3-w6",
                            Date = new DateTime(2025, 4, 2, 17, 12, 35, 246, DateTimeKind.Local).AddTicks(6159),
                            Description = "Focuses on quads, hamstrings, calves, and glutes",
                            Name = "Lower Body Strength"
                        },
                        new
                        {
                            Id = "1a2b3c4d-5e6f-7a8b-9c0d-1e2f3a4b5c6d",
                            Date = new DateTime(2025, 4, 6, 17, 12, 35, 246, DateTimeKind.Local).AddTicks(6159),
                            Description = "A comprehensive workout that targets all major muscle groups",
                            Name = "Full Body Workout"
                        },
                        new
                        {
                            Id = "2b3c4d5e-6f7a-8b9c-0d1e-2f3a4b5c6d7e",
                            Date = new DateTime(2025, 4, 8, 17, 12, 35, 246, DateTimeKind.Local).AddTicks(6159),
                            Description = "Targets chest, shoulders, back, and arms",
                            Name = "Upper Body Focus"
                        },
                        new
                        {
                            Id = "3c4d5e6f-7a8b-9c0d-1e2f-3a4b5c6d7e8f",
                            Date = new DateTime(2025, 4, 9, 17, 12, 35, 246, DateTimeKind.Local).AddTicks(6159),
                            Description = "Focuses on quads, hamstrings, calves, and glutes",
                            Name = "Lower Body Strength"
                        });
                });

            modelBuilder.Entity("gym_prog.Data.Entities.Exercise", b =>
                {
                    b.HasOne("gym_prog.Data.Entities.Workout", "Workout")
                        .WithMany("Exercises")
                        .HasForeignKey("WorkoutId");

                    b.Navigation("Workout");
                });

            modelBuilder.Entity("gym_prog.Data.Entities.Workout", b =>
                {
                    b.Navigation("Exercises");
                });
#pragma warning restore 612, 618
        }
    }
}
